ems-project/EMSCommonBundle

Common/EMSLink.php

Content types can also contain _

bugfix: emsLink regex content type

---

Helper/EmsFields.php
Resources/config/twig.xml
Storage/Processor/Config.php
Storage/Processor/Processor.php
Storage/StorageManager.php
Twig/RequestRuntime.php
composer.json

Useful when generating a PDF (template), it's possible to directly generate the processed file and retrieve a file path with the option _get_file_path: true option

Ready: Get file path

---

Storage/Service/AbstractUrlStorage.php

because of another process holding the file

Under windows (antivirus issue?) the rename is not always working

---

Entity/JsonMenu.php
Helper/Text/Decoder.php
Resources/config/services.xml
Twig/CommonExtension.php
Twig/TextRuntime.php

New json menu decode (function and filter)

Ems json menu decode

---

Entity/JsonMenu.php

New convenient function to directly retrieve an item from its uid from a Json Menu array

feat: new convenient function to directly retrieve an item from its uid

---

Twig/CommonExtension.php
Twig/TextRuntime.php

New ems_json_decode twig filter

Feat(twig): new ems_json_decode filter

---

Entity/JsonMenu.php
Storage/Processor/Processor.php
Storage/Processor/StreamRange.php
Twig/CommonExtension.php
Twig/TextRuntime.php

|Fixed tickets  ||	
MDK pushed some commits directly to MASTER, they are needed in develop to prevent double review and conflicts!

Sync develop with master

---

DependencyInjection/Configuration.php
DependencyInjection/EMSCommonExtension.php
Resources/config/storage.xml
Storage/Processor/Processor.php
Storage/StorageManager.php

feat(storage): add S3 support to skeleton

---

Service/Pdf/DomPdfPrinter.php
Service/Pdf/PdfOutput.php
Service/Pdf/PdfPrinterInterface.php
phpstan-baseline.neon

|Bug fix?       |yes|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
This PR is required for submissionBundle 2.0 (https://github.com/ems-project/EMSSubmissionBundle/pull/31)

Feat submission 2.0

---

Storage/Processor/Config.php

hotfix: return types processor config

---

Storage/Processor/Config.php

|New feature?   |no|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
Bugfix return types config processor

Release 1.8.13

---

Contracts/ExpressionServiceInterface.php
Resources/config/services.xml
Service/ExpressionService.php
composer.json

|Bug fix?       |no|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|	
public contract EMS\CommonBundle\Contracts\ExpressionServiceInterface

Feat: expression service

---

Contracts/ExpressionServiceInterface.php
Resources/config/services.xml
Service/ExpressionService.php
Storage/Processor/Config.php
composer.json

|Bug fix?       |no|
|New feature?   |yes|	
|BC breaks?     |no|	
|Deprecations?  |no|	
|Fixed tickets  |no|

Release 1.8.14

---

Common/EMSLink.php
Elasticsearch/Document/Document.php
EventListener/CommandListener.php
Storage/Service/HttpStorage.php
Storage/StorageServiceMissingException.php
Twig/CommonExtension.php
phpstan-baseline.neon

Fix/type from contenttype with deprecate 

---

Common/EMSLink.php
Elasticsearch/Document/Document.php
EventListener/CommandListener.php
Exception/DateTimeCreationException.php
Resources/config/services.xml
Search/Search.php
Service/ElasticaService.php
Storage/Service/HttpStorage.php
Storage/StorageServiceMissingException.php
Twig/CommonExtension.php
phpstan-baseline.neon

- fix: type from contenttype with deprecate
- feat: elastica service

Release 1.8.19

---

src/Service/ElasticaService.php

feat(elastica): get elasticsearch version

---

src/Command/StatusCommand.php
src/Resources/config/services.xml
src/Service/ElasticaService.php

feat: new ems:status command

---

phpstan-baseline.neon
src/Elasticsearch/Aggregation/Aggregation.php
src/Elasticsearch/Aggregation/Bucket.php
src/Elasticsearch/Aggregation/ElasticaAggregation.php
src/Elasticsearch/Document/Document.php
src/Elasticsearch/Exception/SingleResultException.php
src/Elasticsearch/Response/Response.php
src/Search/Search.php
src/Service/ElasticaService.php

feat(es7): Response's isAccurate method

---

src/Elasticsearch/Aggregation/Aggregation.php

feat: Aggregation:getKeys method

---

src/Resources/config/storage.xml
src/Storage/Factory/FileSystemFactory.php

fix: Relative path support

---

src/Storage/Factory/FileSystemFactory.php

fix: create fs folder if missing

---

src/Resources/config/storage.xml
src/Storage/Factory/FileSystemFactory.php

Release 1.8.26

---

src/Resources/config/twig.xml
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php

feat: ems_unzip

---

src/Resources/config/twig.xml
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php

release: 1.8.27 

---

src/Storage/Factory/EntityFactory.php
src/Storage/Factory/FileSystemFactory.php
src/Storage/Factory/HttpFactory.php
src/Storage/Factory/S3Factory.php
src/Storage/Factory/SftpFactory.php
src/Storage/Factory/StorageFactoryInterface.php
src/Storage/Service/AbstractUrlStorage.php
src/Storage/Service/EntityStorage.php
src/Storage/Service/FileSystemStorage.php
src/Storage/Service/HttpStorage.php
src/Storage/Service/S3Storage.php
src/Storage/Service/SftpStorage.php
src/Storage/Service/StorageInterface.php
src/Storage/StorageManager.php
src/Twig/RequestRuntime.php

Feat/read-only and to-skip storage services

---

src/Storage/Factory/AbstractFactory.php

fix: setDefaults for storage type

---

src/Service/ElasticaService.php

Avoid any direct dependency to elastica from emsco and emsch

feat: new getTermsQuery function and new filter by contentTypes in generateTermsSearch

---

src/Service/ElasticaService.php

WIP: feat: convertElasticsearchSearch method

---

src/Elasticsearch/Response/Response.php
src/Service/ElasticaService.php

Release 1.8.33

---

src/Storage/StorageManager.php

After using the file upload in elasticms
Unable to find file "@EMSCommonBundle/src/Resources/public/images/big-logo.png".

fix: not found big-logo.png

---

src/Service/ElasticaService.php

feat: getClusterHealth

---

src/Service/ElasticaService.php

feat: getClusterInfo

---

src/Service/ElasticaService.php

Replace_With_One_Paragraph_Description

Release 1.8.35

---

src/Elasticsearch/Aggregation/Aggregation.php

fix: create bucket object on the fly

---

phpstan-baseline.neon
src/Logger/ElasticsearchLogger.php

|BC breaks?     |Y|	
|Deprecations?  |Y|	

refactor: migrate to elastica

---

doc/image-processor.md

doc: image processor

---

src/Storage/Processor/Image.php

feat: chore new phpstan

---

doc/image-processor.md
phpstan-baseline.neon
src/Elasticsearch/Document/EMSSource.php
src/Elasticsearch/Mapping.php
src/Logger/ElasticsearchLogger.php
src/Resources/config/services.xml
src/Storage/Processor/Image.php

Release 1.3.38

---

src/Storage/Factory/FileSystemFactory.php
src/Storage/Factory/S3Factory.php

feat: if the S3 parameters are empty

---

src/Logger/ElasticsearchLogger.php

Release 1.3.39

---

src/Logger/ElasticsearchLogger.php
src/Storage/Factory/FileSystemFactory.php
src/Storage/Factory/S3Factory.php
src/Storage/Processor/Image.php

fix: missed phpcs + avoid error on write log if elasticsearch is missing

---

src/Logger/ElasticsearchLogger.php
src/Storage/Factory/FileSystemFactory.php
src/Storage/Factory/S3Factory.php
src/Storage/Processor/Image.php

Release 1.8.40

---

src/Storage/Processor/Image.php

fix: cast to int

---

src/Service/ElasticaService.php
src/Storage/Processor/Image.php

Release 1.8.43

---

src/Storage/Processor/Image.php

fix: cast to int in image processor

---

src/Storage/Processor/Image.php

Releae 1.8.44

---

src/Helper/EmsFields.php
src/Logger/ElasticsearchLogger.php

Add the console.terminate support in order to purge the log's queue. And a a log with the outcome to the command (exit code)

feat: log command terminate (and ensure to purge log's queue)

---

composer.json

https://github.com/ems-project/EMSClientHelperBundle/issues/143

chore: twig 2.14

---

src/Resources/config/profiler.xml
src/Resources/config/services.xml

This service is required by the elastica factory

fix: issue in prod mode whith ems_common.logger.elastica

---

src/Elasticsearch/Aggregation/Aggregation.php
src/Elasticsearch/Aggregation/Bucket.php
src/Elasticsearch/Client.php
src/Logger/ElasticaLogger.php
src/Search/Search.php
src/Service/ElasticaService.php

fix: agg contentType multiple indices

---

src/Service/ElasticaService.php
src/Storage/Service/AbstractUrlStorage.php

This is a new helper function (getIndicesFromAlias) in the elasticaservice to get all indices referenced in an alias

feat: getIndicesFromAlias

---

src/Elasticsearch/Aggregation/Bucket.php
src/Service/ElasticaService.php

fix: scroll setIndices

---

src/Service/ElasticaService.php

fix: rollback refactoring

---

src/Elasticsearch/Aggregation/Bucket.php
src/Service/ElasticaService.php

Release 1.8.48

---

src/Service/ElasticaService.php

suggest query attribute has been replaced by suggest_field

fix: ignore suggest with es7 and after

---

src/Service/ElasticaService.php

Release 1.8.49

---

composer.json
doc/twig.md
src/Helper/Text/Encoder.php
src/Twig/CommonExtension.php

New ems_markdown twig filter converting a markdown string (github standards) into an html string

feat: new ems_markdown twig filter

---

.github/workflows/code_quality.yml
.php_cs.dist
composer.json
phpstan-baseline.neon
phpstan.neon.dist

Github actions cfr maintainer bundle

chore: github actions

---

doc/common.md
src/Common/ArrayHelper/RecursiveMapper.php

Add helper class for recursively map values on array

feat: add array recursive mapper

---

.github/workflows/code_quality.yml
.php_cs.dist
composer.json
doc/common.md
phpstan-baseline.neon
phpstan.neon.dist
src/Common/ArrayHelper/RecursiveMapper.php

- Add github actions
- Add array recursive mapper

release 1.8.54

---

src/Json/JsonMenuNested.php

fix: setObject on json menu nested

---

doc/common.md
src/Common/ArrayHelper/RecursiveMapper.php

Release 1.8.55

---

src/Json/JsonMenuNested.php

fix: setLabel on JsonMenuNested

---

src/Json/JsonMenuNested.php

release: 1.8.56

---

src/Json/JsonMenuNested.php
src/Service/ElasticaService.php

Release 1.8.57

---

composer.json
src/Common/SpreadsheetGeneratorService.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php
src/Resources/config/services.xml
tests/Unit/Common/SpreadsheetGeneratorTest.php

|Bug fix?       |No|
|New feature?   |Yes|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |No|	
Service to allow spreadsheet exports based on JSON.

[FEAT] Spreadsheet export service

---

composer.json
phpstan-baseline.neon
src/Common/SpreadsheetGeneratorService.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php
src/Resources/config/services.xml
src/Storage/Processor/Image.php
tests/Unit/Common/SpreadsheetGeneratorTest.php

- Spreadsheet export service (#229)
- The \ceil function image resize (#230)

Release 1.8.58

---

src/Common/Standard/DateTime.php

feat: standard datetime

---

src/Service/ElasticaService.php

https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-your-data.html#track-total-hits

fix: es7 track total hits

---

src/Service/ElasticaService.php

fix: no track total for _count

---

src/Common/Standard/DateTime.php

By default the search total counter is limited to 10.000. If there is more results es is still displaying 10.000

Release 1.8.60

---

src/Service/ElasticaService.php

- add elastica refresh [#241](https://github.com/ems-project/EMSCommonBundle/pull/241)

release 1.8.63

---

.github/workflows/commit_quality.yml

https://github.com/ems-project/maintainers/issues/17

ci: Commit quality

---

.github/workflows/commit_quality.yml
src/Service/ElasticaService.php

- update gitignore [#243](https://github.com/ems-project/EMSCommonBundle/pull/243)
- commit Quality [#245](https://github.com/ems-project/EMSCommonBundle/pull/245)

release: 1.8.64

---

composer.json
src/Service/ElasticaService.php

- feat: add a post_filter support [#246](https://github.com/ems-project/EMSCommonBundle/pull/246)

build: 1.8.65

---

src/DependencyInjection/EnvVarProcessor/UrlEncodeEnvVarProcessor.php
src/Resources/config/services.xml

- feat: urlencode env variables #250

Release 1.8.66

---

src/Storage/StorageManager.php

Get the list of storage services where an asset can be found

feat: get the list of storages where an assets can be located

---

src/Storage/StorageManager.php

List storages where an asset can be located

build: 1.8.67

---

src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php

feat: ems temp file filter

---

src/Storage/StorageManager.php
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php

|BC breaks?     |y|	
|Deprecations?  |y|	
|Fixed tickets  |y|	
New ems_temp_file twig filter

Release 1.8.68

---

src/Service/ElasticaService.php

- fix a deprecation message issue in elasticsearch 6 and 7 (which may have a huge impact to the server log's size)
- avoid nested bool query in some cases for es6 and es7

build: 1.8.69

---

composer.json
doc/processors.md
phpstan-baseline.neon
src/Helper/EmsFields.php
src/Storage/Processor/Config.php
src/Storage/Processor/Image.php

feat: image filp and rotate

---

composer.json
doc/processors.md
phpstan-baseline.neon
src/Common/EMSLink.php
src/Helper/EmsFields.php
src/Helper/Text/Encoder.php
src/Storage/Processor/Config.php
src/Storage/Processor/Image.php

|Fixed tickets  |Y|	
- Add _rotate, _auto_rotate, _flip_horizontal, _flip_vertical functionalities to image processor
- New mimetype to font awsome class encoder

build: 1.8.70

---

.github/workflows/code_quality.yml
composer.json
src/Service/Pdf/DomPdfPrinter.php
src/Service/Pdf/PdfPrintOptions.php

- fix: dompdf chroot (#262)
- fix: image 0.12.88 (#263)

build: 1.8.71

---

src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/CoreApiFactory.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Resources/config/services.xml
src/Storage/Service/HttpStorage.php

Add functions to the CoreAPI in order to chunk upload files

feat: core api upload

---

src/Command/StatusCommand.php
src/Common/Command/AbstractCommand.php

feat: common AbstractCommand

---

src/Command/StatusCommand.php
src/Common/Command/AbstractCommand.php
src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/CoreApiFactory.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Resources/config/services.xml
src/Storage/Service/HttpStorage.php

- core api upload (#266)
- common AbstractCommand (#265)

build: 1.8.72

---

src/Search/Search.php
src/Service/ElasticaService.php

feat: search source excludes

---

src/Elasticsearch/Aggregation/Aggregation.php

- remove dep getRaw aggregation (#273)

build: 1.8.73 (part 2)

---

src/Common/SpreadsheetGeneratorService.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php
tests/Unit/Common/SpreadsheetGeneratorTest.php

|Bug fix?       ||
|New feature?   ||	
|BC breaks?     ||	
|Deprecations?  ||	
|Fixed tickets  ||	
- Add CSV support to the Spreadsheet generator

build: 1.8.74

---

src/Common/Command/AbstractCommand.php

fix: add ems_process_command

---

src/Common/Command/AbstractCommand.php

- add EMS_PROCESS_COMMAND (#278)

build: 1.8.75

---

src/Search/Search.php
src/Service/ElasticaService.php

Exception: Unknown key for a VALUE_STRING in [0].
Example
```twig
{% set body = { "_source": { "excludes": [ "content" ] } } %}
```

fix: report view type core exclude _source

---

src/Common/Command/AbstractCommand.php
src/Search/Search.php
src/Service/ElasticaService.php

build: 1.8.76

---

src/Command/CommandInterface.php

feat: add consts execute results

---

src/Command/CommandInterface.php

- feat: add consts execute results (#282)

build: 1.8.77

---

doc/json-menu-nested.md
doc/json-menu.md
src/Json/JsonMenu.php
src/Json/JsonMenuNested.php

- Add a breadcrumb iterator to the JsonMenu object
- Add a contains method in order to know if a UID is present in a JsonMenu structure

feat: breadcrumb

---

doc/json-menu-nested.md
doc/json-menu.md
src/Command/CommandInterface.php
src/Json/JsonMenu.php
src/Json/JsonMenuNested.php

build: 1.8.78

---

doc/json-menu-nested.md
phpstan-baseline.neon
src/EventListener/CommandListener.php
src/Json/JsonMenuNested.php

Breadcrumb in reverse order (JsonMenuNested)

feat: reverse breadcrumb

---

src/Common/Command/AbstractCommand.php

chore: choices abstract command

---

doc/json-menu-nested.md
doc/json-menu.md
doc/processors.md
doc/storages.md
doc/twig.md
phpstan-baseline.neon
src/Common/Document.php
src/Common/HttpClientFactory.php
src/Controller/FileController.php
src/DependencyInjection/EMSCommonExtension.php
src/EMSCommonBundle.php
src/Exception/DateTimeCreationException.php
src/Helper/ArrayTool.php
src/Helper/Text/Encoder.php
src/Logger/FlashMessageLogger.php
src/Resources/config/storage.xml
src/Service/Pdf/PdfGenerator.php
src/Service/Pdf/PdfPrintOptions.php
tests/Unit/Helper/CacheTest.php

refactor: phpstan part 2

---

src/Common/Command/AbstractCommand.php

Abstract command's input array getters

feat: abstract command's input array getters

---

src/Elasticsearch/Response/Response.php
src/Resources/config/twig.xml

chore: missing hints

---

doc/json-menu-nested.md
src/Json/JsonMenuNested.php

feat: json menu nested search

---

doc/json-menu-nested.md
src/Common/Command/AbstractCommand.php
src/Elasticsearch/Response/Response.php
src/Json/JsonMenuNested.php
src/Resources/config/twig.xml

build: 1.8.82

---

src/Json/JsonMenuNested.php

feat: json menu nested getItemById

---

src/Json/JsonMenuNested.php

build: 1.8.82 (part 2)

---

src/Common/EMSLink.php
src/Helper/EmsFields.php
src/Service/Pdf/DomPdfPrinter.php
src/Service/Pdf/PdfGenerator.php
src/Service/Pdf/PdfPrintOptions.php
src/Storage/Processor/Config.php
src/Twig/AssetRuntime.php

build: 1.8.83

---

src/Common/EMSLink.php
src/Elasticsearch/Document/EMSSource.php
src/Elasticsearch/Document/EMSSourceInterface.php

feat: improve es doc and emsLink

---

src/Json/JsonMenuNested.php

fix: setChildren jsonMenuNested

---

src/Common/EMSLink.php
src/Elasticsearch/Document/EMSSource.php
src/Elasticsearch/Document/EMSSourceInterface.php
src/Json/JsonMenuNested.php

build: 1.8.84

---

doc/twig.md
src/Helper/Text/Encoder.php
src/Resources/config/services.xml
src/Twig/CommonExtension.php
src/Twig/TextRuntime.php

feat: twig filter ems_replace_regex

---

doc/twig.md
src/Helper/Text/Encoder.php
src/Resources/config/services.xml
src/Twig/CommonExtension.php
src/Twig/TextRuntime.php

build: 1.8.85

---

src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/Data/Data.php
src/Common/CoreApi/Endpoint/File/File.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/Data/DataInterface.php
src/Contracts/CoreApi/Endpoint/Data/FileInterface.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php

Improve the core api:
- uploadFile
- head
- headFile
- createOrUpdateAndFinalize
- createOrReplaceAndFinalize

feat: extended api

---

src/Repository/AssetStorageRepository.php
src/Storage/Service/AbstractUrlStorage.php
src/Storage/Service/EntityStorage.php
src/Storage/Service/HttpStorage.php
src/Storage/Service/StorageInterface.php
src/Storage/StorageManager.php

in case of error or copy;  to save space and allow the user to retry another upload

fix: Delete the uploaded file 

---

doc/contracts.md
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/File/DataExtract.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/File/DataExtractInterface.php

New extract data endpoint client call

feat: extract data api endpoint

---

src/Common/CoreApi/Search/Scroll.php

Fix an error when the scroll doesn't have result

fix: empty scroller

---

src/Elasticsearch/Document/Document.php
src/Elasticsearch/Document/DocumentInterface.php
tests/Unit/Elasticsearch/Document/DocumentTest.php

Helper function to get a field value from a Document object

feat: document get value function

---

doc/storages.md
src/Common/CoreApi/Search/Scroll.php
src/Elasticsearch/Document/Document.php
src/Elasticsearch/Document/DocumentInterface.php
src/Storage/Factory/S3Factory.php
src/Storage/Service/S3Storage.php
src/Storage/StorageManager.php
tests/Unit/Elasticsearch/Document/DocumentTest.php

build: 1.8.91

---

src/Common/Standard/Json.php

feat: JSON::escape

---

src/Common/CoreApi/Endpoint/File/File.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php

feat: file as stream api

---

src/Common/CoreApi/Endpoint/File/File.php
src/Common/Standard/Json.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php

build: 1.8.93

---

composer.json
doc/commands.md
src/Command/CurlCommand.php
src/Command/StatusCommand.php
src/Commands.php
src/Resources/config/services.xml

feat: curl command

---

composer.json
doc/commands.md
src/Command/CurlCommand.php
src/Command/StatusCommand.php
src/Commands.php
src/Resources/config/services.xml

build:  1.8.94

---

composer.json
src/Search/Search.php

build: 1.8.95

---

src/Common/Standard/Json.php
tests/Unit/Common/Standard/JsonTest.php

feat: isJson method

---

src/Common/Standard/Json.php
tests/Unit/Common/Standard/JsonTest.php

build: 1.8.96

---

composer.json
src/Twig/AssetRuntime.php

chore: phpstan

---

composer.json
doc/processors.md
src/Helper/EmsFields.php
src/Storage/Processor/Config.php
src/Storage/StorageManager.php
src/Twig/AssetRuntime.php

build: 1.8.97

---

src/Entity/AssetStorage.php
src/Entity/EntityInterface.php

feat: EntityInterface

---

src/Entity/AssetStorage.php
src/Entity/EntityInterface.php

build: 1.8.98

---

composer.json
src/Command/ClearLogsCommand.php
src/Commands.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Entity/Log.php
src/Helper/Logger/DoctrineHandler.php
src/Repository/LogRepository.php
src/Resources/config/services.xml

- monolog doctrine handler
- Clear doctrine logs command

feat: monolog doctgrine handler

---

src/Helper/Log/LocalizedLogger.php
src/Resources/config/services.xml

feat: localized logger

---

composer.json
src/Command/ClearLogsCommand.php
src/Commands.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Entity/Log.php
src/Helper/Log/LocalizedLogger.php
src/Helper/Logger/DoctrineHandler.php
src/Repository/LogRepository.php
src/Resources/config/services.xml

build: 1.8.99

---

src/Contracts/Elasticsearch/QueryLoggerInterface.php
src/DependencyInjection/EMSCommonExtension.php
src/Elasticsearch/Client.php
src/Elasticsearch/ElasticaLogger.php
src/Resources/config/contracts.xml
src/Resources/config/services.xml

Add query logger contract for enabling or disabling the query logging

feat: contract query logger

---

src/Entity/Log.php
src/Helper/Logger/DoctrineHandler.php

feat: log impersonator

---

src/Common/Standard/Hash.php
src/Service/ElasticaService.php

feat: elastic get url + Hash standard

---

src/Common/Standard/Hash.php
src/Service/ElasticaService.php

build: 1.18.101

---

doc/twig.md
src/Common/Text/EmsHtml.php
src/Twig/CommonExtension.php
src/Twig/TextRuntime.php

feat: ems text twig

---

doc/twig.md
src/Common/Text/EmsHtml.php
src/Twig/CommonExtension.php
src/Twig/TextRuntime.php

build: 1.8.101 (part2)

---

src/Entity/Log.php
src/Helper/Logger/DoctrineHandler.php

The logger may broken entities by flushing the entity manager when it"s not expected.

fix: execute statement not entity to insert log

---

doc/processors.md
src/Helper/EmsFields.php
src/Storage/Processor/Config.php
src/Storage/Processor/Image.php
src/Storage/Processor/Processor.php

Add a _image_format config attribute to the image processor

feat: image formats

---

doc/processors.md
src/Entity/Log.php
src/Helper/EmsFields.php
src/Helper/Logger/DoctrineHandler.php
src/Storage/Processor/Config.php
src/Storage/Processor/Image.php
src/Storage/Processor/Processor.php

build: 1.8.103

---

src/Common/SpreadsheetGeneratorService.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php

build: 1.18.104

---

src/Common/Standard/Json.php

feat: prettier jsons

---

src/Common/SpreadsheetGeneratorService.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php

feat: generate spreadsheets as files

---

src/Common/SpreadsheetGeneratorService.php

refactor: name hint

---

doc/spreadsheet.md
src/Command/Admin/GetCommand.php
src/Command/Admin/LoginCommand.php
src/Command/Admin/UpdateCommand.php
src/Common/Admin/AdminHelper.php
src/Common/Admin/ConfigHelper.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/Admin/Admin.php
src/Common/CoreApi/Endpoint/Admin/Config.php
src/Common/SpreadsheetGeneratorService.php
src/Common/Standard/Json.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/Admin/AdminInterface.php
src/Contracts/CoreApi/Endpoint/Admin/ConfigInterface.php
src/Contracts/SpreadsheetGeneratorServiceInterface.php
src/DependencyInjection/EMSCommonExtension.php
src/Resources/config/commands.xml
src/Resources/config/services.xml
tests/Unit/Common/SpreadsheetGeneratorTest.php

build: 1.8.105

---

composer.json
phpstan-baseline.neon
phpstan.neon.dist
src/Command/CurlCommand.php
src/Common/CoreApi/Endpoint/File/File.php
src/Common/SpreadsheetGeneratorService.php
src/Elasticsearch/Document/DocumentCollectionInterface.php

Allow to be required by a Symfony 5.4 project

chore: add 5.4

---

src/Command/Document/DownloadCommand.php
src/Command/Document/UpdateCommand.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/Meta/Meta.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/Admin/MetaInterface.php
src/Elasticsearch/Document/Document.php
src/Elasticsearch/Document/DocumentInterface.php
src/Resources/config/commands.xml

ems:document:download and ems:document:update commands

feat: download update documents

---

src/Command/Document/DownloadCommand.php
src/Command/Document/UpdateCommand.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/Meta/Meta.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/Admin/MetaInterface.php
src/Elasticsearch/Document/Document.php
src/Elasticsearch/Document/DocumentInterface.php
src/Resources/config/commands.xml

build: 2.0.2

---

src/Common/Document.php
src/Common/EMSLink.php

feat: Document.getEmsLink

---

src/Common/Document.php
src/Common/EMSLink.php
src/Common/Standard/Type.php
tests/Unit/Common/Standard/TypeTest.php

build: 2.0.3

---

doc/twig.md
src/Resources/config/services.xml
src/Twig/CommonExtension.php
src/Twig/SearchRuntime.php

feat: ems_nested_search

---

doc/twig.md
src/Resources/config/services.xml
src/Twig/CommonExtension.php
src/Twig/SearchRuntime.php

build: 2.0.4

---

src/Elasticsearch/Factory.php
src/Storage/Processor/Config.php
src/Storage/Processor/Image.php
src/Storage/Service/EntityStorage.php
src/Storage/StorageManager.php
tests/Unit/Common/SpreadsheetGeneratorTest.php
tests/Unit/Helper/CacheTest.php
tests/Unit/Helper/Text/EncoderTest.php

in some cases the stream is not rewind

fix: rewind if needed

---

src/Twig/CommonExtension.php

feat: ems base64 twig filter

---

src/Common/File/FileReader.php
src/Contracts/File/FileReaderInterface.php
src/Resources/config/contracts.xml
src/Resources/config/services.xml

feat: file reader contract

---

src/Common/CoreApi/Endpoint/Data/Data.php
src/Common/Standard/Image.php
src/Contracts/CoreApi/Endpoint/Data/DataInterface.php

feat: api data save discard draft

---

src/Common/SpreadsheetGeneratorService.php
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php

build: 2.0.8

---

doc/core-api.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php

Auto create a CoreApi from environment variables EMS_BACKEND_URL.
Add new environment parameter EMS_BACKEND_API_KEY
https://github.com/ems-project/website-skeleton/pull/107
https://github.com/ems-project/elasticms/pull/209

feat: coreApi from config

---

doc/core-api.md
src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApi.php
src/Common/CoreApi/Endpoint/Form/Form.php
src/Common/CoreApi/Result.php
src/Contracts/CoreApi/CoreApiInterface.php
src/Contracts/CoreApi/Endpoint/Form/FormInterface.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
tests/Unit/Common/CoreApi/Form/FormTest.php

build: 2.0.9

---

src/Controller/MetricController.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Resources/config/metric.xml

fix: metric port config

---

src/Controller/MetricController.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Resources/config/metric.xml

build: 2.1.1

---

src/Common/EMSLink.php

build: 2.1.2

---

doc/commands.md
doc/common.md
src/Command/ClearLogsCommand.php
src/Common/Command/AbstractCommand.php
src/Common/Log/DoctrineHandler.php
src/Entity/Log.php
src/Repository/LogRepository.php
src/Resources/config/log.xml

|Deprecations?  n||	
The log entity should have an ouuid from the context, this way we can show revision related logs on the revision page (audit).
Also refactored the doctrineHandler to use the LogRepository
The doctrine migration is add in this pr: https://github.com/ems-project/EMSCoreBundle/pull/1122

feat: log ouuid

---

doc/commands.md
doc/common.md
src/Command/ClearLogsCommand.php
src/Common/Command/AbstractCommand.php
src/Common/Log/DoctrineHandler.php
src/Entity/Log.php
src/Repository/LogRepository.php
src/Resources/config/log.xml

build: 2.1.3 (part 2)

---

composer.json
src/Twig/AssetRuntime.php

fix: avoid issues in generating pdf if an asset is missing

---

composer.json
src/Twig/AssetRuntime.php

build: 2.1.4

---

src/Common/EMSLink.php
src/Repository/LogRepository.php
src/Storage/Factory/AbstractFactory.php
src/Storage/Factory/FileSystemFactory.php
src/Storage/Processor/Config.php
src/Twig/AssetRuntime.php
tests/Unit/Helper/CacheTest.php

https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.9.1
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.9.2

chore: php-cs-fixer new version

---

src/Storage/Service/AbstractUrlStorage.php
src/Storage/Service/FileSystemStorage.php
src/Storage/Service/HttpStorage.php
src/Storage/Service/S3Storage.php
src/Storage/Service/SftpStorage.php

fix: s3 seekable

---

src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApiFactory.php
src/Common/CoreApi/Endpoint/File/File.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Resources/config/services.xml

For local develop, we can now configure the common bundle coreApi as insecure.

feat: insecure core api

---

composer.json
phpunit.xml.dist
src/Common/CoreApi/Client.php
src/Common/CoreApi/CoreApiFactory.php
src/Common/CoreApi/Endpoint/File/File.php
src/Common/EMSLink.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSCommonExtension.php
src/Helper/Text/Encoder.php
src/Json/JsonMenuNested.php
src/Repository/LogRepository.php
src/Resources/config/services.xml
src/Storage/Factory/AbstractFactory.php
src/Storage/Factory/FileSystemFactory.php
src/Storage/Processor/Config.php
src/Storage/Service/AbstractUrlStorage.php
src/Storage/Service/FileSystemStorage.php
src/Storage/Service/HttpStorage.php
src/Storage/Service/S3Storage.php
src/Storage/Service/SftpStorage.php
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php
tests/Unit/Helper/ArrayToolTest.php
tests/Unit/Helper/CacheTest.php
tests/Unit/Json/JsonMenuNestedTest.php
tests/Unit/Json/json_menu_nested_1.json
tests/Unit/Json/json_menu_nested_2.json

- #427 
- #428 
- #432 
- #431 
- #433
- #429

build: 2.2.0

---

src/Common/CoreApi/Endpoint/File/File.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php

feat: improve upload file

---

src/Common/CoreApi/Endpoint/File/File.php
src/Contracts/CoreApi/Endpoint/File/FileInterface.php

build: 2.2.0 (part2)

---

src/Helper/Text/Encoder.php

webalize always returns a string, never a string

refactor: webalize never null

---

src/Common/Text/EmsHtml.php
src/Helper/Text/Encoder.php

build: 2.2.2

---

src/Json/JsonMenuNested.php
tests/Unit/Json/JsonMenuNestedTest.php

build: 2.2.3
