ems-project/EMSCommonBundle

Common/HttpClientFactory.php
Storage/Processor/Processor.php
Storage/Service/HttpStorage.php

Because the backend ems is redirect, we need to use guzzle http client.
Implement a streamInterface callback for the streamedResponse.

bugfix: use guzzle for http storage

---

Helper/EmsFields.php
Storage/Processor/Config.php
Storage/Processor/Processor.php
Storage/StorageManager.php
Twig/RequestRuntime.php

I added a new asset config parameters _file_names. This parameters can contains an array of files. If one of this file exists it will be used to be processed by the asset processor. So there is no need to specify a hash if you have at least on file referred in this parameter.
Bellow an example with Aperture. I have beside my elasticms an Aperture database. Aperture generated a lot of previews directly in it's DB. As I dont want to duplicates all those images and I do not want to loose time to register them in ems I can process them directly from my twigs:
`{# the list of potential files from my external source#}
{% set fileNames = {} %}
{% if source.imageProxy.fullSizePreviewPath %}
{% set fileNames = fileNames|merge(['/Users/theus/Pictures/Aperture\ …

Processor use files

---

Storage/Processor/Processor.php

Quick debug to avoid to save generated assets (like cropped images) are saved on too many (or too slow) storage services.

Limit the save of generated assets to 1 storage service

---

Controller/FileController.php
Helper/EmsFields.php
Helper/Text/Encoder.php
Logger/ElasticsearchLogger.php
Storage/Processor/Config.php
Storage/Processor/Image.php
Storage/Processor/Processor.php
composer.json
tests/Unit/Helper/Text/EncoderTest.php

if the _background asset config attribute is set to #FF0000 or #FF000000, the background will be red without transparency. With #FF0000FF it will be fully transparent. It works only if the _quality is set to 0 and than if a PNG is generated

Support transparancy for the _background image processor's attribute

---

Helper/Text/Encoder.php

|Deprecations?  |Y|	
Prepare the migration to PHP 7.4

bug[twig]: dash in ulr pattern are not escaped in regex

---

Storage/Service/S3Storage.php

some s3 systems, such NetApp StorageGRID, might return false on \rename call in parent::finalizeUpload as S3 doesn't support rename

fix: S3 doesn't supports \rename

---

src/Service/ElasticaService.php

Add getHealthStatus method in elasticaService.
IMPORTANT:
Running the following code was causing a big memory usage on a big
cluster.
$client->getCluster()->getHealth()->getStatus();

feat: elastica service health status

---

src/Storage/Factory/AbstractFactory.php
src/Storage/Factory/EntityFactory.php
src/Storage/Factory/HttpFactory.php
src/Storage/Factory/SftpFactory.php
src/Storage/Service/StorageInterface.php

fix: default usage attribute value must be a string (not a int)

---

src/Search/Search.php
src/Service/ElasticaService.php

Add an addTermsAggregation in the Search object, add generateTermsSearch and getBoolQuery functions to the elastica service in order to avoid direct dependencies to elastica in emsch and emsco bundles

feat: addTermsAggregation, generateTermsSearch and getBoolQuery functions

---

src/Elasticsearch/Response/Response.php

Notice: Trying to access array offset on value of type int
in \vendor/elasticms/common-bundle/src/Elasticsearch/Response/Response.php (line34)

fix: access array offset bug es response

---

src/Logger/ElasticsearchLogger.php

The _contenttype logs field value can be override per service instance

feat: content type name for logs

---

src/Elasticsearch/ElasticaFactory.php

|BC breaks?     |Y|	
Elastica hardcod the scheme in http in it's client. Hopefully there is an `url` option which can be used to defined the curl base url.  But using that url always expect a trailing url.

fix: use the url parameter when the scheme is not in http

---

src/Service/ElasticaService.php

By default the first 10 documents are fetch. If they are huge this query significantly slow down the request.

fix: Perf issue on getIndicesForContentTypes 

---

src/Service/ElasticaService.php

|BC breaks?     |y|	
|Deprecations?  |y|	
|Fixed tickets  |y|	
The local push command for clientHelperBundle was not getting correct results after doing api updates.
It seems the elasticSearch index needs to forced to refresh.

feat: add elastica refresh

---

.gitignore
composer.json
src/Service/ElasticaService.php

Add the post_filter support in the convertElasticsearchBody function. 
I also discover the Simple query object which can simply convert an array into an Elastica query object. So I took the opportunity to refactor the convertElasticsearchBody function in order to avoir bool query with a single must sub-query

feat: add a post_filter support

---

src/Service/ElasticaService.php

Query on the field _type triggers a warning message on elasticsearch 7 and testing _type for elk is useless as we need to rely on the filed _contenttype.

fix: it's useless to test the _type for ELK6 and after

---

.github/workflows/code_quality.yml

Keep the previous phpstan image to stay in php 7

fix: image 0.12.88

---

src/Elasticsearch/Document/Document.php

Sadly the getRaw is currently used by the clientHelperBundle.
In the feature we should deprecate this function but for now it's too strict.

chore: remove dep getRaw on document

---

src/Elasticsearch/Aggregation/Aggregation.php

The clientHelper search is using this for searching. Too soon for a deprecation.

chore: remove dep getRaw aggregation

---

doc/processors.md
phpstan-baseline.neon
src/Resources/config/twig.xml
src/Storage/Processor/Processor.php
src/Twig/AssetRuntime.php
src/Twig/CommonExtension.php
src/Twig/RequestRuntime.php
src/Twig/TextRuntime.php

|Fixed tickets  |y|	
- _mime_type config attribute can be used to override the file field's mimetype
- close #70

refactor: twig runtimes to asset

---

src/Resources/config/twig.xml

asset runtime id alias is missing

chore: missing alias

---

doc/storages.md
src/Storage/Factory/S3Factory.php
src/Storage/Service/S3Storage.php
src/Storage/StorageManager.php

- add an upload-folder option to the S3 storage service
- Memory leak on finalise upload (switched to a streamed hash compute instead of loading the uploaded file in a string)

feat: s3 upload folder

---

composer.json
src/Search/Search.php

Wrong version of symfony/serializer

fix: align serializer to symfony 4.4

---

doc/processors.md
src/Helper/EmsFields.php
src/Storage/Processor/Config.php
src/Storage/StorageManager.php

ems_asset_path returns immutable routes, so if the _file_names is define in ordre to use a local file, the config file must reflects the file signature. So the config hash will change if the file chamge.

fix: ensure that the config hash change if the file change

---

src/Command/Admin/GetCommand.php
src/Command/Admin/UpdateCommand.php
src/Common/Admin/ConfigHelper.php
src/Common/Command/AbstractCommand.php
src/Resources/config/commands.xml

get a default json filename from /opt/src/admin/%config-type%/%entity-name%.json in order to have simplier command: `ems:admin:update content-type route`

feat: update wo json path

---

src/Command/Admin/LoginCommand.php

Because the default is now EMS_BACKEND_URL environment variable, it should be at last position.
For better usage standalone, the username and password became options
```bash
php bin/console ems:admin:login http://myelasticms.test 
> Username 
> Password
php bin/console ems:admin:login http://myelasticms.test -u david
> Password
php bin/console ems:admin:login --username davmat
> Password
```

fix: admin login url last argument

---

src/Common/Log/DoctrineHandler.php
src/Common/Log/LocalizedLogger.php
src/Common/Log/LocalizedLoggerFactory.php
src/Contracts/Log/LocalizedLoggerFactoryInterface.php
src/Contracts/Log/LocalizedLoggerInterface.php
src/DependencyInjection/EMSCommonExtension.php
src/Resources/config/contracts.xml
src/Resources/config/log.xml
src/Resources/config/services.xml

Created a new namespace Common\Log which should contain all logging classes.
The service 'ems.logger' will be moved to the CoreBundle, for now it's only used there. But now we can define multiple loggers and define the translation domain + channel. Not all 'app'
Before
```xml
<service id="ems.logger" alias="ems_common.localized_logger"/>
<service id="ems_common.localized_logger" class="EMS\CommonBundle\Helper\Log\LocalizedLogger">
<argument type="service" id="logger" />
<argument type="service" id="translator" />
</service>
```
Now (in the core)
```xml
<service id="ems.logger" class="EMS\CommonBundle\Contracts\Log\LocalizedLoggerInterface"> …
```

refactor(log): common log namespace

---

src/Helper/Text/Encoder.php

When we use webalize for creating a slug from a title, and the title ends with a point. 
We can only points for files, but not as last character.

fix: webalize point at end, only allow for ext

---

composer.json
phpunit.xml.dist
src/Json/JsonMenuNested.php
tests/Unit/Helper/ArrayToolTest.php
tests/Unit/Helper/CacheTest.php
tests/Unit/Json/JsonMenuNestedTest.php
tests/Unit/Json/json_menu_nested_1.json
tests/Unit/Json/json_menu_nested_2.json

Improved the json menu nested object, for better php functions.
The core needs to compare to jsonMenuNested objects
- Implemented Countable interface
- New function `filterChildren(callable $callback): JsonMenuNested`. This can not be used from twig!
- New function `diffChildren(JsonMenuNested $compareJsonMenuNested): JsonMenuNested`
- Add new function changeId, allows to fix duplicated ids inside a structure. 
- GetChildren and getPath now allow an optional callback argument. Easy printing in php.
- New function `addChild` & `addChildByArray`
- New function `hasChild`

feat: json menu nested diff
